### ISSUE TITLE
Woodcutter Job

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#5499]
#### Which modpack version are you using?
Live Version
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
I tried to harvest a redwood bark.
#
#### What happened instead? (Attach screenshots if needed)
It didn't reward any money nor increase the woodcutter jobs level.
#
#### What do you suggest instead/what changes do you propose?
copy the setting from Delta to Eta.

EDIT: Same goes for most of the natura woods.
IDs:
650
650:1
650:2
650:3
651
651:1
651:2
657
665
665:15
668
668:1
686
686:1
686:2
686:3
797

**Comment by Dream-Master** [comment]
copy and paste not workes because every server have different ids.

Using your ids and look if i could add it.

**Comment by Dream-Master** [comment]
797 was in there allread.
I add the other gives 1.5 points
````
 650:
        income: 1.5
        points: 1.5
        experience: 1.5
      650-1:
        income: 1.5
        points: 1.5
        experience: 1.5
      650-2:
        income: 1.5
        points: 1.5
        experience: 1.5
      650-3:
        income: 1.5
        points: 1.5
        experience: 1.5
      651:
        income: 1.5
        points: 1.5
        experience: 1.5
      651-1:
        income: 1.5
        points: 1.5
        experience: 1.5
      651-2:
        income: 1.5
        points: 1.5
        experience: 1.5
      657:
        income: 1.5
        points: 1.5
        experience: 1.5
      665:
        income: 1.5
        points: 1.5
        experience: 1.5
      665-15:
        income: 1.5
        points: 1.5
        experience: 1.5
      668:
        income: 1.5
        points: 1.5
        experience: 1.5
      668-1:
        income: 1.5
        points: 1.5
        experience: 1.5
      686:
        income: 1.5
        points: 1.5
        experience: 1.5
      686-1:
        income: 1.5
        points: 1.5
        experience: 1.5
      686-2:
        income: 1.5
        points: 1.5
        experience: 1.5
      686-3:
        income: 1.5
        points: 1.5
        experience: 1.5
      797:
        income: 1.5
        points: 1.5
        experience: 1.5
````
